<?php
if ( function_exists( "register_field_group" ) ) {
	register_field_group( array(
		'id'         => 'acf_articles',
		'title'      => 'Articles',
		'fields'     => array(
			array(
				'key'          => 'field_563b84491ff82',
				'label'        => 'Image de bandeau',
				'name'         => 'img_bandeau',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'header-formation',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'post',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'side',
			'layout'         => 'default',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_auteur',
		'title'      => 'Auteur',
		'fields'     => array(
			array(
				'key'          => 'field_55cce19c79a65',
				'label'        => 'Image de profil',
				'name'         => 'avatar',
				'type'         => 'image',
				'instructions' => 'Mettre l\'image en 82x82 px',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'ef_user',
					'operator' => '==',
					'value'    => 'all',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'no_box',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_business-case',
		'title'      => 'Business case',
		'fields'     => array(
			array(
				'key'           => 'field_55ccd2c909cdc',
				'label'         => 'Entreprise',
				'name'          => 'entreprise',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_55ccd2dc09cdd',
				'label'         => 'Détail de la prestation',
				'name'          => 'prestation',
				'type'          => 'text',
				'instructions'  => 'Ex : Formation intra-entreprise - Programme sur mesure - 30 salariés – 1 programme – 2 formateurs',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_55ccd65438191',
				'label'         => 'Durée',
				'name'          => 'duree',
				'type'          => 'text',
				'instructions'  => 'Ex : ½ jour à 2 jours',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_55ccd6c7625e1',
				'label'         => 'Objectif',
				'name'          => 'objectif',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_55ccd33209cde',
				'label'         => 'Descriptif de la mission',
				'name'          => 'descriptif',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'             => 'field_55ccd35609cdf',
				'label'           => 'Témoignages',
				'name'            => 'temoignage',
				'type'            => 'relationship',
				'return_format'   => 'object',
				'post_type'       => array(
					0 => 'temoignage',
				),
				'taxonomy'        => array(
					0 => 'all',
				),
				'filters'         => array(
					0 => 'search',
				),
				'result_elements' => array(
					0 => 'post_type',
					1 => 'post_title',
				),
				'max'             => '',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'businesscase',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'default',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_formateurs',
		'title'      => 'Formateurs',
		'fields'     => array(
			array(
				'key'   => 'field_55c1d997963eb',
				'label' => 'Profil',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_559aa4a48062d',
				'label'        => 'Avatar',
				'name'         => 'avatar',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
			array(
				'key'           => 'field_55966a9fece59',
				'label'         => 'Spécialité',
				'name'          => 'specialite',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_55967af00e759',
				'label'         => 'biographie',
				'name'          => 'biographie',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'yes',
			),
			array(
				'key'          => 'field_559d466f36202',
				'label'        => 'Réseaux sociaux',
				'name'         => 'reseaux',
				'type'         => 'repeater',
				'sub_fields'   => array(
					array(
						'key'           => 'field_559d46ac8e9ab',
						'label'         => 'Réseau social',
						'name'          => 'reseau',
						'type'          => 'select',
						'required'      => 1,
						'column_width'  => '',
						'choices'       => array(
							'google'   => 'Google+',
							'facebook' => 'Facebook',
							'twitter'  => 'Twitter',
							'viadeo'   => 'Viadeo',
							'linkedin' => 'Linkedin',
						),
						'default_value' => '',
						'allow_null'    => 0,
						'multiple'      => 0,
					),
					array(
						'key'           => 'field_559d467636203',
						'label'         => 'Url du profil',
						'name'          => 'url',
						'type'          => 'text',
						'column_width'  => '',
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
				),
				'row_min'      => '',
				'row_limit'    => '',
				'layout'       => 'table',
				'button_label' => 'Ajouter un réseau social',
			),
			array(
				'key'   => 'field_55c1d9b7963ec',
				'label' => 'Vidéo',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_55966aac0e756',
				'label'         => 'Titre de la video',
				'name'          => 'video_titre',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_55966ad20e757',
				'label'         => 'Lien de la vidéo',
				'name'          => 'video_url',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'          => 'field_55967a4f0e758',
				'label'        => 'Image de la video',
				'name'         => 'video_image',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'ef_taxonomy',
					'operator' => '==',
					'value'    => 'formateur',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'no_box',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_formations',
		'title'      => 'Formations',
		'fields'     => array(
			array(
				'key'           => 'field_558d1ac129603',
				'label'         => 'Top formation',
				'name'          => 'top_formation',
				'type'          => 'true_false',
				'message'       => '',
				'default_value' => 0,
			),
			array(
				'key'          => 'field_55ca098082128',
				'label'        => 'Image d\'entête de bloc',
				'name'         => 'image_header_formation',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'header-formation',
				'library'      => 'all',
			),
			array(
				'key'           => 'field_55952a4d0cf11',
				'label'         => 'Nombre de jours de la formation',
				'name'          => 'nombre_jours',
				'type'          => 'number',
				'default_value' => 1,
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'min'           => '',
				'max'           => '',
				'step'          => '',
			),
			array(
				'key'   => 'field_55c1cef63c180',
				'label' => 'Thématique',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_55c1cf053c181',
				'label'        => 'Picto',
				'name'         => 'picto',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'           => 'field_55c139fbab249',
				'label'         => 'Texte d\'introduction de la thématique',
				'name'          => 'intro_thematique',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'   => 'field_55c13a24ab24a',
				'label' => 'Présentation',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_55c13c9ef3a2f',
				'label'        => 'Visuel de présentation',
				'name'         => 'visuel_presentation',
				'type'         => 'image',
				'instructions' => 'Taille 569x253 px',
				'save_format'  => 'url',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
			array(
				'key'           => 'field_558d15c8d8df6',
				'label'         => 'Présentation',
				'name'          => 'presentation',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'         => 'field_559506baed64a',
				'label'       => 'Fiche de la formation',
				'name'        => 'fiche_formation',
				'type'        => 'file',
				'save_format' => 'url',
				'library'     => 'all',
			),
			array(
				'key'   => 'field_559e923e18287',
				'label' => 'Le programme',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_559505cfed646',
				'label'         => 'Programme - colonne 1',
				'name'          => 'programme_1',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_55c13d5ff3a31',
				'label'         => 'Programme - colonne 2',
				'name'          => 'programme_2',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_55c13d5ef3a30',
				'label'         => 'Programme - colonne 3',
				'name'          => 'programme_3',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'   => 'field_559e92e97bb27',
				'label' => 'Informations',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_559505e2ed647',
				'label'         => 'Informations pratiques',
				'name'          => 'informations',
				'type'          => 'wysiwyg',
				'instructions'  => 'Présenter un liste à puce !',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_55c13e0290199',
				'label'         => 'Prérequis de la formation',
				'name'          => 'prerequis_formation',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_55c13e409019a',
				'label'         => 'A qui s’adresse cette formation',
				'name'          => 'pour_qui',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'   => 'field_559e93137bb28',
				'label' => 'Objectifs',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_55950817ed64c',
				'label'         => 'Texte d\'introduction',
				'name'          => 'intro_objectifs',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_559e932c7bb29',
				'label'         => 'Objectifs - colonne 1',
				'name'          => 'objectifs_1',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'           => 'field_55c13eb09019b',
				'label'         => 'Objectifs - colonne 2',
				'name'          => 'objectifs_2',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'basic',
				'media_upload'  => 'no',
			),
			array(
				'key'   => 'field_559e91e718286',
				'label' => 'Sessions',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_55951917b6249',
				'label'        => 'Les sessions',
				'name'         => 'sessions',
				'type'         => 'repeater',
				'sub_fields'   => array(
					array(
						'key'            => 'field_55951969b624a',
						'label'          => 'Date',
						'name'           => 'date_session',
						'type'           => 'date_picker',
						'column_width'   => '',
						'date_format'    => 'yy-mm-dd',
						'display_format' => 'dd/mm/yy',
						'first_day'      => 1,
					),
					array(
						'key'           => 'field_55951a8ab624b',
						'label'         => 'Lieu',
						'name'          => 'lieu_session',
						'type'          => 'text',
						'column_width'  => '',
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
					array(
						'key'           => 'field_55951aa8b624d',
						'label'         => 'ouvert',
						'name'          => 'ouvert',
						'type'          => 'true_false',
						'column_width'  => '',
						'message'       => '',
						'default_value' => 0,
					),
				),
				'row_min'      => '',
				'row_limit'    => '',
				'layout'       => 'table',
				'button_label' => 'Ajouter une session',
			),
			array(
				'key'   => 'field_55c14c97ecca7',
				'label' => 'Témoignages',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'             => 'field_55c14ca7ecca8',
				'label'           => 'Témoignages',
				'name'            => 'temoignages',
				'type'            => 'relationship',
				'return_format'   => 'object',
				'post_type'       => array(
					0 => 'temoignage',
				),
				'taxonomy'        => array(
					0 => 'all',
				),
				'filters'         => array(
					0 => 'search',
				),
				'result_elements' => array(
					0 => 'post_type',
					1 => 'post_title',
				),
				'max'             => '',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'formation',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'default',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_options',
		'title'      => 'Options',
		'fields'     => array(
			array(
				'key'   => 'field_55e40bcf8906f',
				'label' => 'Gestion des pages',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'        => 'field_55c133086a3fc',
				'label'      => 'Page de demande de catalogue',
				'name'       => 'page_demande_catalogue',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'        => 'field_55c4735f1725e',
				'label'      => 'Page formations',
				'name'       => 'page_nos_formations',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'        => 'field_55db55814f266',
				'label'      => 'Page d\'inscription newsletter',
				'name'       => 'page_newsletter',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'           => 'field_55c52c260b461',
				'label'         => 'Page des témoignages',
				'name'          => 'page_temoignages',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'        => 'field_55dc14e659de3',
				'label'      => 'Page thématiques',
				'name'       => 'page_thematiques',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'        => 'field_55e953d04f98b',
				'label'      => 'Page références',
				'name'       => 'page_references',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'        => 'field_55dc150059de4',
				'label'      => 'Page calendrier',
				'name'       => 'page_calendrier',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'        => 'field_55c132bb6a3fb',
				'label'      => 'Page de contact',
				'name'       => 'page_contact',
				'type'       => 'page_link',
				'post_type'  => array(
					0 => 'page',
				),
				'allow_null' => 1,
				'multiple'   => 0,
			),
			array(
				'key'           => 'field_55c13a66c533e',
				'label'         => 'Téléphone',
				'name'          => 'telephone',
				'type'          => 'text',
				'default_value' => '09 77 21 53 21',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_55c1de5dc8481',
				'label'         => 'Url chaine Dailymotion',
				'name'          => 'url_dailymotion',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'   => 'field_55e40be789070',
				'label' => 'Slider page d\'accueil',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_55e40bf889071',
				'label'        => 'Slides',
				'name'         => 'slides',
				'type'         => 'repeater',
				'sub_fields'   => array(
					array(
						'key'          => 'field_55e40c2589072',
						'label'        => 'Image',
						'name'         => 'image',
						'type'         => 'image',
						'column_width' => 100,
						'save_format'  => 'url',
						'preview_size' => 'medium',
						'library'      => 'all',
					),
					array(
						'key'           => 'field_55e40c3f89073',
						'label'         => 'Titre',
						'name'          => 'titre',
						'type'          => 'text',
						'column_width'  => 33,
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
					array(
						'key'           => 'field_55e40c5789074',
						'label'         => 'Sous titre',
						'name'          => 'sous_titre',
						'type'          => 'text',
						'column_width'  => 33,
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
					array(
						'key'           => 'field_55e40c5f89075',
						'label'         => 'Lien',
						'name'          => 'lien',
						'type'          => 'text',
						'column_width'  => 33,
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
					array(
						'key'           => 'field_561e1e2e18df6',
						'label'         => 'Video',
						'name'          => 'video',
						'type'          => 'text',
						'column_width'  => '',
						'default_value' => '',
						'placeholder'   => '',
						'prepend'       => '',
						'append'        => '',
						'formatting'    => 'html',
						'maxlength'     => '',
					),
					array(
						'key'           => 'field_566043ef127a6',
						'label'         => 'Plus d\'infos',
						'name'          => 'more_color',
						'type'          => 'color_picker',
						'column_width'  => '',
						'default_value' => '',
					),
				),
				'row_min'      => '',
				'row_limit'    => '',
				'layout'       => 'row',
				'button_label' => 'Ajouter un slide',
			),
			array(
				'key'   => 'field_55eff6eab9589',
				'label' => 'Images de Une',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'          => 'field_55eff721b958a',
				'label'        => 'Etudes de cas',
				'name'         => 'img_etudes_de_cas',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55eff747b958b',
				'label'        => 'Le catalogue de nos formations',
				'name'         => 'img_nos_formations',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55eff78ab958c',
				'label'        => 'Dans les médias',
				'name'         => 'img_dans_les_medias',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55eff7a5b958e',
				'label'        => 'Références',
				'name'         => 'img_references',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55eff7b8b958f',
				'label'        => 'Témoignages',
				'name'         => 'img_temoignages',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55eff7cbb9590',
				'label'        => 'Nos vidéos',
				'name'         => 'img_nos_videos',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55effc071efc9',
				'label'        => 'Nos formateurs',
				'name'         => 'img_nos_formateurs',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55effc221efca',
				'label'        => 'Nos thématiques',
				'name'         => 'img_nos_thematiques',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_55f1a442655f0',
				'label'        => 'Blog',
				'name'         => 'img_blog',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'          => 'field_560127c3efc52',
				'label'        => 'Recherche',
				'name'         => 'img_recherche',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'full',
				'library'      => 'all',
			),
			array(
				'key'   => 'field_563b80921ec2e',
				'label' => 'Sous titre',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_563b8251ec5ab',
				'label'         => 'Témoignages',
				'name'          => 'testimony_sub_title',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'   => 'field_55fa90dae6850',
				'label' => 'Textes d\'intro',
				'name'  => '',
				'type'  => 'tab',
			),
			array(
				'key'           => 'field_55fa90ffe6851',
				'label'         => 'Dans les médias',
				'name'          => 'intro_dans_les_medias',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'yes',
			),
			array(
				'key'           => 'field_55fa9125e6852',
				'label'         => 'Nos vidéos',
				'name'          => 'intro_nos_videos',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'yes',
			),
			array(
				'key'           => 'field_5615636ae8e85',
				'label'         => 'Formations',
				'name'          => 'intro_formations',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'yes',
			),
			array(
				'key'           => 'field_564d911df7ede',
				'label'         => 'Témoignages',
				'name'          => 'intro_temoignages',
				'type'          => 'wysiwyg',
				'default_value' => '',
				'toolbar'       => 'full',
				'media_upload'  => 'yes',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'options_page',
					'operator' => '==',
					'value'    => 'acf-options',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'default',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_references',
		'title'      => 'Références',
		'fields'     => array(
			array(
				'key'           => 'field_55968d9a4902b',
				'label'         => 'url',
				'name'          => 'url',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'reference',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'acf_after_title',
			'layout'         => 'default',
			'hide_on_screen' => array(
				0  => 'permalink',
				1  => 'the_content',
				2  => 'excerpt',
				3  => 'custom_fields',
				4  => 'discussion',
				5  => 'comments',
				6  => 'revisions',
				7  => 'slug',
				8  => 'author',
				9  => 'format',
				10 => 'categories',
				11 => 'tags',
				12 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_temoignages',
		'title'      => 'Témoignages',
		'fields'     => array(
			array(
				'key'           => 'field_5595548e12603',
				'label'         => 'Nom de l\'entreprise',
				'name'          => 'entreprise',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'          => 'field_560e576604299',
				'label'        => 'visuel carré',
				'name'         => 'visuel_carre',
				'type'         => 'image',
				'save_format'  => 'id',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'temoignage',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'no_box',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_thematiques',
		'title'      => 'Thématiques',
		'fields'     => array(
			array(
				'key'          => 'field_558ac79f960ef',
				'label'        => 'Picto',
				'name'         => 'picto',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'thumbnail',
				'library'      => 'all',
			),
			array(
				'key'           => 'field_559bc6e51a5c7',
				'label'         => 'Couleur',
				'name'          => 'couleur',
				'type'          => 'select',
				'choices'       => array(
					'gray'      => 'Gris',
					'orange'    => 'Orange',
					'yellow'    => 'Jaune',
					'green'     => 'Vert',
					'blue'      => 'Bleu',
					'blue-dark' => 'Bleu foncé',
				),
				'default_value' => '',
				'allow_null'    => 0,
				'multiple'      => 0,
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'ef_taxonomy',
					'operator' => '==',
					'value'    => 'thematique',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'no_box',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_type-formationreference',
		'title'      => 'Type formation/reference',
		'fields'     => array(
			array(
				'key'          => 'field_563c8b69dfc49',
				'label'        => 'Image bandeau',
				'name'         => 'img_bandeau',
				'type'         => 'image',
				'save_format'  => 'url',
				'preview_size' => 'header-formation',
				'library'      => 'all',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'ef_taxonomy',
					'operator' => '==',
					'value'    => 'type',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
			array(
				array(
					'param'    => 'ef_taxonomy',
					'operator' => '==',
					'value'    => 'type-reference',
					'order_no' => 0,
					'group_no' => 1,
				),
			),
		),
		'options'    => array(
			'position'       => 'normal',
			'layout'         => 'no_box',
			'hide_on_screen' => array(),
		),
		'menu_order' => 0,
	) );
	register_field_group( array(
		'id'         => 'acf_pages',
		'title'      => 'Pages',
		'fields'     => array(
			array(
				'key'           => 'field_558bcdc46000f',
				'label'         => 'Sous titre',
				'name'          => 'sous_titre',
				'type'          => 'text',
				'default_value' => '',
				'placeholder'   => '',
				'prepend'       => '',
				'append'        => '',
				'formatting'    => 'html',
				'maxlength'     => '',
			),
			array(
				'key'           => 'field_558bce3d60011',
				'label'         => 'Fond',
				'name'          => 'fond',
				'type'          => 'color_picker',
				'default_value' => '',
			),
			array(
				'key'           => 'field_559e910c23289',
				'label'         => 'Texte d\'introduction',
				'name'          => 'texte_introduction',
				'type'          => 'textarea',
				'default_value' => '',
				'placeholder'   => '',
				'maxlength'     => '',
				'rows'          => '',
				'formatting'    => 'br',
			),
		),
		'location'   => array(
			array(
				array(
					'param'    => 'post_type',
					'operator' => '==',
					'value'    => 'page',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options'    => array(
			'position'       => 'acf_after_title',
			'layout'         => 'default',
			'hide_on_screen' => array(),
		),
		'menu_order' => 1,
	) );
}
